sudo: true
language: python
python:
  - 3.6
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce

before_script:
  - pip install -r requirements.txt
  - set -e
  - docker build -t $docker_username/web-link-tester .
  - docker run -d -p 80:80 $docker_username/web-link-tester
  - sleep 5
script:
  - pytest -v --cov=lib --cov=tests --disable-pytest-warnings
  - curl -X POST --data "https://github.com" http://localhost/api

deploy:
  - provider: script
    script: bash ./deploy.sh
    on:
      branch: master